### ISSUE TITLE
Please, be aware: Echelon chain/project is scam

### ISSUE THREAD

**Issue by alpha-omega-labs** [osmosis-labs/assetlists#205]
Please, take a look at this closely:
https://github.com/ethereum-lists/chains/issues/1216
https://github.com/ethereum-lists/chains/issues/1216#issuecomment-1146469051
https://twitter.com/mr_ligi/status/1532866855257399296

**Comment by sunnya97** [comment]
Thanks for sharing this.  We will not be adding the asset to the main frontend at this time.  Frontier is meant to be more permissionless.

**Comment by jonator** [comment]
Osmosis chain can't prevent assets from being IBC transferred; thus making it truly permission-less. The frontier version of the frontend takes on the same attitude: it is simply a tool that makes it convenient to access everything on the Osmosis chain.

Though, I agree we should caution users about such assets on frontier.

**Comment by alpha-omega-labs** [comment]
Completely understandable!
Just some heads up to keep Osmosis front end clean and community aware. 
Thank you.
