### ISSUE TITLE
Make CI check correctness of all IBC denoms

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/assetlists#267]
We should make a CI job that checks correctness of all the IBC hashes.

Basically doing automatically what Jeremy did here: https://github.com/osmosis-labs/assetlists/pull/266#discussion_r1008391669

**Comment by JeremyParish69** [comment]
Running into the issue with cw20's using a different port. Switching from the ibc object over to traces would help me include the port for those assets.
