### ISSUE TITLE
Generating the assetlist.json file

### ISSUE THREAD

**Issue by JeremyParish69** [osmosis-labs/assetlists#316]
Howdy, y'all. I'm looking to update and further automate the Assetlists repo.

I want to create a small, simple file (exemplified below) in the assetlists repo, and have it be the only file needing to be touched to add a token to the assetlists repo (after having registered the chain and asset):

If would list all the listed assets, ordered as seen on Osmosis Zone, and only contain:
 - minimal asset specification (just base denom and chain name),
 - pool ids,
 - osmosis-specific keywords, and
 - override data, where applicable (rare).

The current assetlist.json file we have now would still exist roughly as is, but no longer be manually modified; it would instead be auto-generated (using the data from this proposed new file and the Chain Registry) whenever an asset is listed or modified.

The generated assetlist.json file will eventually be able to automatically feed into the Osmosis frontend, thus drastically simplifying the manual aspects of listing a token.

```
"assets": [
  {
    "chain_name": "osmosis",
    "base": "uosmo",
    "pools": {
      "ATOM": 1,
      "USDC.axl": 678
    },
    "osmosis-main": true,
    "osmosis-frontier": true,
    "osmosis-info": true
  },
  {
    "chain_name": "osmosis",
    "base": "uion",
    "pools": {
      "OSMO": 2
    },
    "osmosis-main": true,
    "osmosis-frontier": true,
    "osmosis-info": true
  },
  {
    "chain_name": "axelar",
    "base": "uusdc",
    "pools": {
      "OSMO": 678
    },
    "osmosis-main": true,
    "osmosis-frontier": true,
    "osmosis-info": true,
    "override_properties": {
      "symbol": "USDC.axl"
      "logo_URIs": {
        "svg": "https://raw.github.com/chain-registry/main/axelar/images/axlusdc.svg"
      }
    }
  },
...
  {
    "chain_name": "cosmoshub",
    "base": "uatom",
    "pools": {
      "OSMO": 1
    },
    "osmosis-main": true,
    "osmosis-frontier": true,
    "osmosis-info": true
  },
  ....

]
```

Thoughts? Objections? Would greatly appreciate feedback.

**Comment by ValarDragon** [comment]
This sounds great to me!

**Comment by JeremyParish69** [comment]
Once the chain registry is updated to using a mainnets, will update the script, and then can upload here to run automatically (wanting to add chain-registry as a submodule). Will also need to update the readme so people only add the 'zone' entry.

**Comment by JeremyParish69** [comment]
Workflow for generation exists, and it's manually triggered under Actions. Not sure if we eventually want it to be automatically triggered on not.
