### ISSUE TITLE
Script to generate go types

### ISSUE THREAD

**Issue by shrimalmadhur** [osmosis-labs/assetlists#341]
Is there a script that can create `go` types for the asset list schema from the json? Or if there's already generated types in one of the osmosis go library which I can use?

**Comment by JeremyParish69** [comment]
Not that I know of. I also don't know if go types are highly demanded and for which applications.

**Comment by ValarDragon** [comment]
I ran into needing this as well. This PR when merged should solve this for you!

https://github.com/osmosis-labs/assetlists/pull/410
