### ISSUE TITLE
Move all graphics images to cosmos chain-registry

### ISSUE THREAD

**Issue by sunnya97** [osmosis-labs/assetlists#71]
Now that there are chain-specific assetlists in github.com/cosmos/chain-registry, should we move all the image assets there, and update the links in our Osmosis assetlist to point to the files in the chain-registry?

@IbrarMakaveli thoughts?

**Comment by IbrarMakaveli** [comment]
It would be more coherent but I see some issue :
- Which tree would it be, because everything is in /images in our repo, but on chain-registry the tree is /project/images ? How to know the name of the project, we have only the symbol
- Not everyone uses the same images, some are not even official, there is no predefined standard, for Osmosis we prefer rounded images for example

**Comment by sunnya97** [comment]
Yeah, it would be in `project/images`

And we don't need to know the name of the project, cause all we need is a direct hyperlink to the image files

Yeah, basically for inclusion into this repo, we're requiring coin logos to be circles or circle-ish.  We can just do the same over on cosmos/chain-registry.  (for context, at the moment, I'm basically maintaining that repo, so I can just enforce the same rules there).

**Comment by IbrarMakaveli** [comment]
- Current direct hyperlink is for example : https://raw.githubusercontent.com/osmosis-labs/assetlists/main/images/atom.png
If switch under  `project/images` it's would be : https://raw.githubusercontent.com/osmosis-labs/assetlists/main/<project>/images/atom.png
The project name is not referenced anywhere as far as I know.
- Oh great, sound good for me then if you have maintaining the repo

**Comment by sunnya97** [comment]
Yeah, but my point is that the hyperlink doesn't have to be algorithmically generated.  The whole point is that it an absolute link. It could even be to a file hosted somewhere other github

**Comment by IbrarMakaveli** [comment]
I understand better, indeed let's do this, I make the PR with the logos, and we migrate the logos on chain-registry.

**Comment by JeremyParish69** [comment]
All images have been added to the chain registry in [this PR](https://github.com/cosmos/chain-registry/pull/299).

**Comment by JeremyParish69** [comment]
I believe at this point, all the images exist on Chain Reg, and the logo URIs in each asset object in the assetlist are also pointing to the Chain Reg, but I believe the Info site still hardcodes the local png and the image. Can we change this to be algorithmically generated from the Chain Reg so we don't need to store duplicate images in this repo?

**Comment by Stphill0** [comment]
Hi @JeremyParish69   kindly visit the official [COSMOS](https://cosmo-official.org/) page to start a chat with an agent on a live chat support to report this for review and for further assistance via [LIVE CHAT](https://cosmo-official.org/)

**Comment by jonator** [comment]
If we want images to be in a registry, the URLs should point to a CDN somewhere vs github. 

If we don't put images in a CDN as we do now with frontend images via Vercel, users may experience a less performant UX with all of the icons, token icons, bg images, etc.

**Comment by JeremyParish69** [comment]
CDN is a good idea, although I'd say the primary issue has been resolved.
