### ISSUE TITLE
Integration of CW20 token on assetlist

### ISSUE THREAD

**Issue by IbrarMakaveli** [osmosis-labs/assetlists#93]
Sample structure : https://github.com/cosmos/chain-registry/blob/master/terra/assetlist.json#L69 :

- Should we keep "cw20:" at beginning of "denom" and "base" ?
- Change "port" value ("transfer") for IBC it's different for CW20 token
- Should we keep "kind" key or should be optional, or maybe not needed if "cw20:" at beginning of "denom" and "base" ?

@sunnya97 @ValarDragon @dogemos

**Comment by sunnya97** [comment]
iirc, I think type might be a reserved keyword of json schemas

**Comment by ValarDragon** [comment]
Perhaps `asset_type` then?

**Comment by IbrarMakaveli** [comment]
Yep, I think `asset_type` or `type_asset` it's fine

**Comment by sunnya97** [comment]
Okay.  @IbrarMakaveli can you update the assetlist schema both here and in github.com/cosmos/chain-registry
