### ISSUE TITLE
Support optional `synonyms` member to objects in `assets`

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/assetlists#96]
### Problem
There are an increasing number of assets on Osmosis (we're preparing for this to further explode in the future). Some of them are related; frequently within the same project. (Terra, Juno)

### Solution
Adding synonyms would allow people adding assets to specify arbitrary keywords that would help users identify their project.

Once we migrate to assetslist repo, we could pull these terms into our filter/search engine on the frontend. Users could almost "google" for certain assets on the frontend and they'd appear.

Example: for the Terra network, they have a few associated stable coins on Osmosis as well as their native LUNA token. For the stable coins, we could add `Terra` and `LUNA` as synonyms so that when a user searches "Terra" or "LUNA" their stablecoins would magically appear as well.

### Task

- [ ] Update existing assets to include synonym keywords (consider consulting each asset's project's stakeholders)

**Comment by sunnya97** [comment]
I like this idea, I think maybe "keywords" would be a better term than "synonyms"

**Comment by IbrarMakaveli** [comment]
Yep good idea, and `keywords` or `project` is more appropriate I think

**Comment by JeremyParish69** [comment]
Keywords had been added to the chain registry and is already in use herein for Imperator and Frontend signaling.
